sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coverage

script:
  - coverage run --include="aliyun-python-sdk-core/aliyunsdkcore/*" --branch -m pytest aliyun-python-sdk-core/tests/
notifications:
    webhooks: https://oapi.dingtalk.com/robot/send?access_token=096ed387df243a6d60835aadeccc47165f3813bc7cb81cdd0cfeadfd28e3acc1
    email: false
    on_success: change
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
